name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Meal Assistant
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Debug

      - name: Test
        run: dotnet test --no-build --configuration Debug --verbosity normal